BlogProj/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.views.static import serve
from .settings import MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', include('blog.urls')),
    path(r'', include('comments.urls')),
    url(r'^search/', include('haystack.urls')),
    url(r'media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
]

blog/urls.py
from django.conf.urls import url
from blog.feeds import AllPostsRssFeed

from . import views

# 视图函数命名空间
app_name = 'blog'

urlpatterns = [
    # url(r'^$', views.index, name='index'),
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$',
        views.ArchivesView.as_view(), name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
    url(r'^all/rss/$', AllPostsRssFeed(), name='rss'),
]

comments/urls.py
from django.conf.urls import url

from . import views

app_name='comments'
urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment'),
    url(r'^comment/like/$', views.comment_likes, name='comment_likes'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.html import strip_tags
import markdown


class Category(models.Model):
    """
    分类
    """
    name = models.CharField(max_length=100, verbose_name='分类名称')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = '分类'


class Tag(models.Model):
    """
    标签
    """
    name = models.CharField(max_length=100, verbose_name='标签名称')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = '标签'


class Post(models.Model):
    """
    文章
    """

    # 文章标题
    title = models.CharField(verbose_name='标题', max_length=70)

    # 文章正文
    body = models.TextField(verbose_name='正文')

    # 创建时间和更新时间
    created_time = models.DateTimeField(verbose_name='发布时间')
    modified_time = models.DateTimeField(verbose_name='修改时间')

    # 封面图片
    cover_pic = models.ImageField(verbose_name="封面图片", upload_to='post', default='post/post_default.png')

    # 摘要
    excerpt = models.CharField(verbose_name='摘要', max_length=200, blank=True)

    # 分类与标签外键
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='分类')
    tags = models.ManyToManyField(Tag, blank=True, verbose_name='标签')

    # 作者
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='作者')

    # 阅读量
    views = models.PositiveIntegerField(default=0, verbose_name='阅读量')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = '博客'
        verbose_name_plural = '博客'
        ordering = ['-created_time', 'title']

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def save(self, *args, **kwargs):
        if not self.excerpt:
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
                ])
            self.excerpt = strip_tags(md.convert(self.body))[:54]

        super(Post, self).save(*args, **kwargs)

comments/models.py
from django.db import models


class Comment(models.Model):
    """评论模型"""
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=255)
    #url = models.URLField(blank=True)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)

    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE)

    def __str__(self):
        return self.text[:20]

class Like(models.Model):
    """赞"""
    comment = models.ForeignKey('comments.Comment', on_delete=models.CASCADE)
    ip = models.CharField(max_length=100)
    created_time = models.DateTimeField(auto_now_add=True)

class Tread(models.Model):
    """踩"""
    comment = models.ForeignKey('comments.Comment', on_delete=models.CASCADE)
    ip = models.CharField(max_length=100)
    created_time = models.DateTimeField(auto_now_add=True)

blog/views.py
import markdown
from django.shortcuts import get_object_or_404
from django.views.generic import ListView, DetailView
from django.utils.text import slugify
from markdown.extensions.toc import TocExtension

from comments.forms import CommentForm
from .models import Post, Category, Tag

"""
def index(request):
    # 首页文章列表
    post_list = Post.objects.all()
    return render(request, 'blog/index.html',
                  context={'post_list': post_list})
"""


class IndexView(ListView):
    """首页文章类视图"""
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')
        # 调用自己写的 pagination_data 方法获得显示分页导航条需要的数据，见下方。
        pagination_data = self.pagination_data(paginator, page, is_paginated)

        # 将分页导航条的模板变量更新到 context 中，注意 pagination_data 方法返回的也是一个字典。
        context.update(pagination_data)

        # 将更新后的 context 返回，以便 ListView 使用这个字典中的模板变量去渲染模板。
        # 注意此时 context 字典中已有了显示分页导航条所需的数据。
        return context

    def pagination_data(self, paginator, page, is_paginated):
        if not is_paginated:
            # 没有分页，无需显示分页条，返回空
            return {}

        # 左侧页码列表
        left = []

        # 右侧页码列表
        right = []

        # 左侧是否显示省略号
        left_has_more = False

        # 右侧显示省略号
        right_has_more = False

        # 左侧是否显示页码1
        first = False

        # 右侧是否显示最后一个页码
        last = False

        # 当前请求的页码数
        page_number = page.number

        # 总页数
        total_pages = paginator.num_pages

        # 获得整个分页页码列表，比如分了四页，那么就是 [1, 2, 3, 4]
        page_range = paginator.page_range

        if page_number == 1:
            # 如果用户请求的是第一页的数据，那么当前页左边的不需要数据，因此 left=[]（已默认为空）。
            # 此时只要获取当前页右边的连续页码号，
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 right = [2, 3]。
            # 注意这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
            right = page_range[page_number:page_number + 2]

            # 如果最右边的页码号比最后一页的页码号减去 1 还要小，
            # 说明最右边的页码号和最后一页的页码号之间还有其它页码，因此需要显示省略号，通过 right_has_more 来指示。
            if right[-1] < total_pages - 1:
                right_has_more = True

            # 如果最右边的页码号比最后一页的页码号小，说明当前页右边的连续页码号中不包含最后一页的页码
            # 所以需要显示最后一页的页码号，通过 last 来指示
            if right[-1] < total_pages:
                last = True

        elif page_number == total_pages:
            # 如果用户请求的是最后一页的数据，那么当前页右边就不需要数据，因此 right=[]（已默认为空），
            # 此时只要获取当前页左边的连续页码号。
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 left = [2, 3]
            # 这里只获取了当前页码后连续两个页码，你可以更改这els个数字以获取更多页码。
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
            # 如果最左边的页码号比第 2 页页码号还大，
            # 说明最左边的页码号和第 1 页的页码号之间还有其它页码，因此需要显示省略号，通过 left_has_more 来指示。
            if left[0] > 2:
                left_has_more = True

            # 如果最左边的页码号比第 1 页的页码号大，说明当前页左边的连续页码号中不包含第一页的页码，
            # 所以需要显示第一页的页码号，通过 first 来指示
            if left[0] > 1:
                first = True
        else:
            # 用户请求的既不是最后一页，也不是第 1 页，则需要获取当前页左右两边的连续页码号，
            # 这里只获取了当前页码前后连续两个页码，你可以更改这个数字以获取更多页码。
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
            right = page_range[page_number:page_number + 2]

            # 是否需要显示最后一页和最后一页前的省略号
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True

            # 是否需要显示第 1 页和第 1 页后的省略号
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True

        data = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
        }

        return data


class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'

    def get(self, request, *args, **kwargs):
        # 覆写 get 方法的目的是因为每当文章被访问一次，就得将文章阅读量 +1
        # get 方法返回的是一个 HttpResponse 实例
        # 之所以需要先调用父类的 get 方法，是因为只有当 get 方法被调用后，
        # 才有 self.object 属性，其值为 Post 模型实例，即被访问的文章 post
        response = super(PostDetailView, self).get(request, *args, **kwargs)

        # 将文章阅读量 +1
        # 注意 self.object 的值就是被访问的文章 post
        self.object.increase_views()

        # 视图必须返回一个 HttpResponse 对象
        return response

    def get_object(self, queryset=None):
        # 覆写 get_object 方法的目的是因为需要对 post 的 body 值进行渲染
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            TocExtension(slugify=slugify),
        ])
        post = super(PostDetailView, self).get_object(queryset=None)
        post.body = md.convert(post.body)
        post.toc = md.toc
        return post

    def get_context_data(self, **kwargs):
        # 覆写 get_context_data 的目的是因为除了将 post 传递给模板外（DetailView 已经帮我们完成），
        # 还要把评论表单、post 下的评论列表传递给模板。
        context = super(PostDetailView, self).get_context_data(**kwargs)
        form = CommentForm()
        comment_list = self.object.comment_set.all()
        context.update({
            'form': form,
            'comment_list': comment_list,
        })
        return context


class ArchivesView(IndexView):
    """归档页面类视图"""

    def get_queryset(self):
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        return super(ArchivesView, self).get_queryset().filter(created_time__year=year,
                                                               created_time__month=month)


class CategoryView(IndexView):
    """分类页面类视图"""

    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category=cate)


class TagView(IndexView):
    """标签页面类视图"""
    def get_queryset(self):
        tag = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
        return super(TagView, self).get_queryset().filter(tags=tag)

templates/blog/detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block main %}
    <div class="container" style="height:2em;padding-left: 0px;margin-top: 4px;">
        <div style="width: 1.5em;height:1.5em;float: left;">
            <img src="{% static 'blog/img/location.svg' %}"/>
        </div>
        <p style="margin: 0px;height:2em;">您的当前位置: 首页 > 个人博客 > 博客详情</p>
   </div>
    <article class="post post-{{ post.pk }} row-back">
        <header class="entry-header">
            <h1 class="entry-title">{{ post.title }}</h1>
            <div class="entry-meta">
                <span class="post-category"><a href="javascript:void(0)">{{ post.category.name }}</a></span>
                <span class="post-date"><a href="javascript:void(0)"><time class="entry-date"
                                                                           datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                <span class="post-author"><a href="javascript:void(0)">{{ post.author }}</a></span>
                <span class="comments-link"><a href="#comment-area">{{ post.comment_set.count }} 评论</a></span>
                <span class="views-count"><a href="javascript:void(0)">{{ post.views }} 阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            {{ post.body|safe }}
        </div>
    </article>
    {% comment %}<div>
        {% for tag in post.tags.all %}
            {{ tag.name }}
        {% empty %}
            empty
        {% endfor %}
    </div>{% endcomment %}
    <section class="comment-area" id="comment-area">
        <hr>
        <p style="font-size:1.2em;font-family: '微软雅黑';background-color: #C0C0C0;">发表评论</p>
        <form action="{% url 'comments:post_comment' post.pk %}" method="post">
            {% csrf_token %}
            <div style="margin-bottom: 10px;text-align: center;">
                <textarea name="text" class="comment-text" style="width:80%;height: 200px;border-radius: 3px;" placeholder="请输入您的评论～"></textarea>
                <!-- {{ form.text }} -->
                {{ form.text.errors }}
            </div>
            <div style="margin-bottom: 50px;text-align:center;width:100%;float: left;">
                <span>姓名：</span>
                <input type="text" name="name" style="margin-right: 5px;" required="required">
                <!-- {{ form.name }} -->
                {{ form.name.errors }}
                <span>邮箱：</span>
                <input type="email" name="email" style="margin-right: 10px;" required="required">
                <!-- {{ form.email }} -->
                {{ form.email.errors }}
                <input type="submit" value="发布评论">
            </div>
        </form>
        <div class="comment-list-panel" style="margin-top: 100px;">
            <p style="font-size:1.2em;font-family: '微软雅黑';background-color: #C0C0C0;">评论列表，共 <span>{{ post.comment_set.count }}</span> 条评论</p>
            <ul class="comment-list list-unstyled">
                {% for comment in comment_list %}
                    <li class="comment-item">
                        <span class="nickname" style="color: goldenrod;">{{ comment.name }}</span>
                        <time class="submit-date"
                              datetime="{{ comment.created_time }}">{{ comment.created_time }}</time>
                        <div class="text">
                            {{ comment.text }}
                        </div>
                        <div style="width: 100%;height: 20px;text-align: right;margin-top: 20px;">
                            <span class="comment-rel"><a href="#" title="回复">回复</a></span>
                            <a href="#" style="margin-right: 10px;">
                            <img src="{% static 'blog/img/001_18.png' %}" class="likes" title="赞">
                            赞：{{ comment.like_set.count }}
                            </a>
                            <a href="#" style="margin-right: 10px;">
                            <img src="{% static 'blog/img/001_19.png' %}" title="踩">
                            踩：{{ comment.tread_set.count }}
                            </a>
                        </div>
                    </li>
                {% empty %}
                    暂无评论！
                {% endfor %}
            </ul>
        </div>
    </section>
{% endblock main %}
{% block toc %}
    <div class="widget widget-recent-content row-back">
        <div class="aside-title">
            <h3>文章目录</h3>
        </div>
        {{ post.toc|safe }}
    </div>
{% endblock toc %}

templates/blog/index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block main %}
    {% for post in post_list %}
        <article class="post post-{{ result.object.pk }}  row-back">
            <header class="entry-header">
                <h1 class="entry-title title-new">
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </h1>
                <div class="entry-meta meta-new">
                    <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                    <span class="post-date"><a href="#"><time class="entry-date"
                                                              datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                    <span class="post-author"><a href="#">{{ post.author.first_name }}{{ post.author.last_name }}</a></span>
                    <span class="comments-link"><a href="#">{{ post.comment_set.count }} 评论</a></span>
                    <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
                </div>
            </header>
            <div class="entry-content clearfix">
                <div style="width: 20%;height:138px;float: left;overflow: hidden;">
                    <img src="{{ MEDIA_URL }}{{ post.cover_pic }}"/>
                </div>
                <div style="margin-left:23%;min-height: 40px">
                    <p style="word-wrap:break-word;">{{ post.excerpt }}...</p>
                </div>
                <div class="read-more cl-effect-14">
                    <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                </div>
            </div>
        </article>
    {% empty %}
        <div class="no-post">暂时没有发布文章</div>
    {% endfor %}

    {% if is_paginated %}
        <div class="pagination pagination-new">
            <ul class="page-li-1">
                {% if page_obj.has_previous %}
                    <li class="page-li page-style"><a href="?page={{ page_obj.previous_page_number }}" title="上一页">&lt;&lt;</a></li>
                {% endif %}
                {% if first %}
                    <li class="page-style"><a href="?page=1">1</a></li>
                {% endif %}
                {% if left %}
                    {% if left_has_more %}
                        <li class="page-style"><span>...</span></li>
                    {% endif %}
                    {% for i in left %}
                        <li class="page-style"><a href="?page={{ i }}">{{ i }}</a></li>
                    {% endfor %}
                {% endif %}
                <li class="page-selected"><a href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>
                {% if right %}
                    {% for i in right %}
                        <li class="page-style"><a href="?page={{ i }}">{{ i }}</a></li>
                    {% endfor %}
                    {% if right_has_more %}
                        <li class="page-style"><span>...</span></li>
                    {% endif %}
                {% endif %}
                {% if last %}
                    <li class="page-style"><a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a></li>
                {% endif %}
                {% if page_obj.has_next %}
                    <li class="page-li page-style"><a href="?page={{ page_obj.next_page_number }}" title="下一页">&gt;&gt;</a></li>
                {% endif %}
            </ul>
        </div>
    {% endif %}

{% endblock main %}