BlogProj/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.views.static import serve
from .settings import MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', include('blog.urls')),
    path(r'', include('comments.urls')),
    url(r'^search/', include('haystack.urls')),
    url(r'media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
]

blog/urls.py
from django.conf.urls import url
from blog.feeds import AllPostsRssFeed

from . import views

# 视图函数命名空间
app_name = 'blog'

urlpatterns = [
    # url(r'^$', views.index, name='index'),
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$',
        views.ArchivesView.as_view(), name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
    url(r'^all/rss/$', AllPostsRssFeed(), name='rss'),
]

templates/base.html
{% load staticfiles %}
{% load blog_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>KebenSun</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/highlights/github.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">

    <!-- js -->
    <script src="https://cdn.bootcss.com/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
    <script src="https://cdn.bootcss.com/layer/3.0.3/layer.min.js"></script>

    <style type="text/css">
        span.highlighted {
            color: red;
        }
        .banner {
            width: 100%;
            height: 250px;
            background-image: url({% static 'blog/img/banner13.jpg' %});
            background-repeat: no-repeat;
            background-size: cover;
            -moz-background-size: cover;
        }
    </style>
</head>

<body>
<div class="container">
    <header id="site-header" class="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8" style="width: 50%;">
                <div class="logo">
                    <a href="{% url 'blog:index' %}"><img src="{% static 'blog/img/fullLogo.png' %}"/></a>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4" style="width: 50%;">
                <div class="search7 bar7">
                    <form role="search" method="get" id="searchform" action="{% url 'haystack_search' %}">
                        <input type="text" class="search-input" name="q" placeholder="请输入搜索内容...">
                        <button type="submit" class="search-button" style="right: 0px;top: 0px"></button>
                    </form>
                </div>
            </div>
        </div>
    </header>
</div>
<div class="col-md-8 col-sm-7 col-xs-4" style="width: 100%;padding: 0px;height: 60px;background-color: #333333;">
    <nav style="width: 100%;height: 60px;">
        <div style="height:60px;padding-left: 0px" class="container">
            <ul style="margin:0 auto;height:60px;padding:0;">
                <li class="cl-effect-11" style="float: left;padding:0;width:120px;height:60px;line-height: 60px;font-size: 20px;list-style-type: none;text-align: center;background-color: gray;">
                    <a href="{% url 'blog:index' %}" data-hover="首页" class="head" id="head"><span>首页</span></a>
                </li>
                <li class="cl-effect-11" style="float: left;padding:0;width:120px;height:60px;line-height: 60px;font-size: 20px;list-style-type: none;text-align: center;">
                    <a href="javascript:void(0)" data-hover="文章" class="head" id="head"><span>文章<span></a>
                    
                </li>
                <li class="cl-effect-11" style="float: left;padding:0;width:120px;height:60px;line-height: 60px;font-size: 20px;list-style-type: none;text-align: center;">
                    <a href="javascript:void(0)" data-hover="关于" class="head" id="head"><span>关于</span></a>
                </li>
                <li class="cl-effect-11" style="float: left;padding:0;width:120px;height:60px;line-height: 60px;font-size: 20px;list-style-type: none;text-align: center;">
                    <a href="javascript:void(0)" data-hover="联系" class="head" id="head"><span>联系</span></a>
                </li>
            </ul>
        </div>
    </nav>
</div>

<div class="content-body">
    <div class="container">
        <div class="row row-back">
            <main class="col-md-8">
                {% block main %}
                {% endblock main %}
            </main>
            <aside class="col-md-4">
                {% block toc %}
                {% endblock toc %}
                <div class="widget row-back" style="margin-top:20px;">
                    <div class="aside-title">
                        <h3>关注我</h3>
                    </div>
                    <ul class="aside-content">
                        <li class="aside-content-li">
                            <div style="background-image: url({% static 'blog/img/PP.jpg' %});"></div>
                        </li>
                        <li class="aside-content-li-1">
                            <div id="phone" class="qrcode">
                                <img layer-src="{% static 'blog/img/phone.png' %}" src="{% static 'blog/img/phone.svg' %}" title="15698001240" class="hand" />
                            </div>
                            <div id="wechat" class="qrcode">
                                <img layer-src="{% static 'blog/img/wechat.png' %}" src="{% static 'blog/img/weixin.svg' %}" title="sunkechong" class="hand"/>
                            </div>
                            <div id="email">
                                <a href="mailto:sun.kechong@outlook.com"><img src="{% static 'blog/img/mail.svg' %}" title="sun.kechong@outlook.com"/></a>
                            </div>
                            <div id="qq" class="qrcode">
                                <img layer-src="{% static 'blog/img/qq.png' %}" src="{% static 'blog/img/qq.svg' %}" title="380187296" class="hand"/>
                            </div>
                            <div style="float: none;">
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="widget widget-recent-posts row-back">
                    <div class="aside-title">
                        <h3>最新文章</h3>
                    </div>
                    {% get_recent_posts as recent_post_list %}
                    <ul class="aside-content-li-2">
                        {% for post in recent_post_list %}
                            <li>
                                <a href="{{ post.get_absolute_url }}" style="font-size:13px;">{{ post.title }}</a>
                            </li>
                        {% empty %}
                            暂无文章
                        {% endfor %}
                    </ul>
                </div>
                <div class="widget widget-archives row-back">
                    <div class="aside-title">
                        <h3>归档</h3>
                    </div>
                    {% archives as date_list %}
                    <ul class="aside-content-li-2">
                        {% for date in date_list %}
                            <li>
                                <a href="{% url 'blog:archives' date.year date.month %}">{{ date.year }}
                                    年 {{ date.month }} 月</a>
                            </li>
                        {% empty %}
                            暂无归档！
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-category row-back">
                    <div class="aside-title">
                        <h3>分类</h3>
                    </div>
                    {% get_categories as category_list %}
                    <ul class="aside-content-li-2">
                        {% for category in category_list %}
                            <li>
                                <a href="{% url 'blog:category' category.pk %}">{{ category.name }}
                                    <span class="post-count">( {{ category.num_posts }} )</span></a>
                            </li>
                        {% empty %}
                            暂无分类！
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-tag-cloud row-back">
                    <div class="aside-title">
                        <h3>标签</h3>
                    </div>
                    {% get_tags as tag_list %}
                    <ul class="aside-content-li-2 aside-content-li-3">
                        {% for tag in tag_list %}
                            <li class="randomColor">
                                <a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a>
                            </li>
                        {% empty %}
                            &emsp;&emsp;暂无标签！
                        {% endfor %}
                    </ul>
                </div>
                <div class="rss">
                    <a href="{% url 'blog:rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2018 - SunKC Blog  <a href="http://www.miitbeian.gov.cn/">鲁ICP备17018800号</a>
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="{% url 'blog:index' %}">首页</a></li>
            <li><a href="#">博客</a></li>
            <li><a href="#">关于</a></li>
            <li><a href="#">联系</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'blog/js/script.js' %}"></script>
<script>
    (function(){
        var bp = document.createElement('script');
        var curProtocol = window.location.protocol.split(':')[0];
        if (curProtocol === 'https'){
            bp.src = 'https://zz.bdstatic.com/linksubmit/push.js';
        }else{
            bp.src = 'http://push.zhanzhang.baidu.com/push.js';
        }
        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(bp, s);
    })();
</script>
</body>
</html>